# autometa_parameter_sweep.sub
# starter submit file for CHTC autometa parameter sweep jobs
universe = docker
docker_image = jasonkwan/autometa:2.1.0

arguments = $(cluster_method) $(completeness) $(purity) $(cov_stddev_limit) $(gc_stddev_limit) $(community)

initial_dir = $(communityDir)
# NOTE: You will need to replace the following with your packed env path
transfer_input_files = 5mers.am_clr.bhsne.tsv,coverage.tsv,gc_content.tsv,bacteria.markers.tsv,taxonomy.tsv,autometa_binning.sh
executable = ./autometa_binning.sh


log = $(community)_autometa_binning_$(cluster_method)_comp$(completeness)_pur$(purity)_cov$(cov_stddev_limit)_gc$(gc_stddev_limit)_$(Cluster)_$(Process).log
output = $(community)_autometa_binning_$(cluster_method)_comp$(completeness)_pur$(purity)_cov$(cov_stddev_limit)_gc$(gc_stddev_limit)_$(Cluster)_$(Process).out
error = $(community)_autometa_binning_$(cluster_method)_comp$(completeness)_pur$(purity)_cov$(cov_stddev_limit)_gc$(gc_stddev_limit)_$(Cluster)_$(Process).err

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

request_cpus = 4
request_memory = 16GB
request_disk = 2GB
+WantFlocking = true
# +WantGlidein = true
+LongJob = true

Requirements = (Target.HasCHTCStaging == true)

queue communityDir,community,cluster_method,completeness,purity,cov_stddev_limit,gc_stddev_limit from sweep_parameters.txt
# queue communityDir,community,cluster_method,completeness,purity,cov_stddev_limit,gc_stddev_limit from test_sweep_parameters.txt
# queue communityDir,community,cluster_method,completeness,purity,cov_stddev_limit,gc_stddev_limit from 78_156_312_sweep_parameters.txt
# queue communityDir,community,cluster_method,completeness,purity,cov_stddev_limit,gc_stddev_limit from 625_1250_10000Mbp_sweep_parameters.txt
