# Autometa binning job submission to Open Science Grid
# For more info: https://chtc.cs.wisc.edu/uw-research-computing/containers-beyond-chtc.html

universe = vanilla
# NOTE: username/image:tag must be within docker_images.txt at linked file below
# https://github.com/opensciencegrid/cvmfs-singularity-sync/blob/master/docker_images.txt
+SingularityImage = "/cvmfs/singularity.opensciencegrid.org/jasonkwan/autometa:latest"

# NOTE: You should *NOT* include a `docker_image` option in the submit file if using the above setup.
# docker_image = jasonkwan/autometa:latest

# Make sure jobs can access the container staging location
Requirements = (Target.HasCHTCStaging == true) && ( HAS_SINGULARITY || (HasSingularity && HAS_CVMFS_oasis_opensciencegrid_org))

initial_dir = $(community)
transfer_input_files = 5mers.am_clr.bhsne.tsv,coverage.tsv,gc_content.tsv,bacteria.markers.tsv,taxonomy.tsv

arguments = $(cluster_method) $(completeness) $(purity) $(cov_stddev_limit) $(gc_stddev_limit) $(community)
executable = autometa.sh


log = $(community)_autometa_binning_$(cluster_method)_comp$(completeness)_pur$(purity)_cov$(cov_stddev_limit)_gc$(gc_stddev_limit)_$(Cluster)_$(Process).log
output = $(community)_autometa_binning_$(cluster_method)_comp$(completeness)_pur$(purity)_cov$(cov_stddev_limit)_gc$(gc_stddev_limit)_$(Cluster)_$(Process).out
error = $(community)_autometa_binning_$(cluster_method)_comp$(completeness)_pur$(purity)_cov$(cov_stddev_limit)_gc$(gc_stddev_limit)_$(Cluster)_$(Process).err

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

request_cpus = 4
request_memory = 16GB
request_disk = 4GB

+WantFlocking = true
+WantGlidein = true

# https://support.opensciencegrid.org/support/solutions/articles/12000083468-indicate-the-duration-category-of-your-jobs
# Medium = 20 hr max
# Long = 40 hr max
+JobDurationCategory = "Long”

queue cluster_method,completeness,purity,cov_stddev_limit,gc_stddev_limit from sweep_parameters.txt
queue community from communities.txt
